import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Future word",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <header>

          <nav>

            <ul>

             <a href="/">

             <li>Home</li>

              </a>

             <a href="/store">
             
             <li>Store</li>

             </a> 

            </ul>

          </nav>

        </header>

        {children}
        </body>
    </html>
  );
}
